#######################################################################
# Setup
#######################################################################

enable_testing()

#######################################################################
# Python unit testing
#######################################################################

message( STATUS "Adding ENDFtk Python unit testing" )

add_test( NAME ENDFtk.python.ControlRecord COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_ControlRecord.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.ControlRecord PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.DirectoryRecord COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_DirectoryRecord.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.DirectoryRecord PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.InterpolationRecord COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_InterpolationRecord.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.InterpolationRecord PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.ListRecord COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_ListRecord.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.ListRecord PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.TabulationRecord COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_TabulationRecord.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.TabulationRecord PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.TapeIdentification COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_TapeIdentification.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.TapeIdentification PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})

add_test( NAME ENDFtk.python.CovariancePairs COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_CovariancePairs.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.CovariancePairs PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.RectangularMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_RectangularMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.RectangularMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.SquareMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_SquareMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.SquareMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})

add_test( NAME ENDFtk.python.MF1.MT451.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT451_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT451.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT452.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT452_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT452.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT455.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT455_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT455.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT455.DecayConstants COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT455_DecayConstants.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT455.DecayConstants PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT455.EnergyDependentConstants COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT455_EnergyDependentConstants.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT455.EnergyDependentConstants PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT455.EnergyIndependentConstants COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT455_EnergyIndependentConstants.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT455.EnergyIndependentConstants PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT456.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT456_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT456.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT458.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT458_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT458.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT458.EnergyReleaseComponent COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT458_EnergyReleaseComponent.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT458.EnergyReleaseComponent PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT458.PolynomialComponents COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT458_PolynomialComponents.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT458.PolynomialComponents PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT458.TabulatedComponents COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT458_TabulatedComponents.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT458.TabulatedComponents PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT458.ThermalPointComponents COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT458_ThermalPointComponents.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT458.ThermalPointComponents PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT460.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT456_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT460.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT460.ContinuousPhotons COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT460_ContinuousPhotons.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT460.ContinuousPhotons PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT460.DiscretePhotonMultiplicity COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT460_DiscretePhotonMultiplicity.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT460.DiscretePhotonMultiplicity PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.MT460.DiscretePhotons COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_MT460_DiscretePhotons.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.MT460.DiscretePhotons PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.PolynomialMultiplicity COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_PolynomialMultiplicity.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.PolynomialMultiplicity PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF1.TabulatedMultiplicity COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF1_TabulatedMultiplicity.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF1.TabulatedMultiplicity PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.BackgroundChannels COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_BackgroundChannels.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.BackgroundChannels PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.BreitWignerLValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_BreitWignerLValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.BreitWignerLValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.FrohnerBackgroundRMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_FrohnerBackgroundRMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.FrohnerBackgroundRMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.Isotope COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_Isotope.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.Isotope PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.MultiLevelBreitWigner COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_MultiLevelBreitWigner.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.MultiLevelBreitWigner PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.NoBackgroundRMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_NoBackgroundRMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.NoBackgroundRMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.ParticlePairs COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_ParticlePairs.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.ParticlePairs PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.ReichMoore COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_ReichMoore.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.ReichMoore PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.ReichMooreLValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_ReichMooreLValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.ReichMooreLValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.ResonanceChannels COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_ResonanceChannels.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.ResonanceChannels PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.ResonanceParameters COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_ResonanceParameters.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.ResonanceParameters PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.RMatrixLimited COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_RMatrixLimited.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.RMatrixLimited PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.SammyBackgroundRMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_SammyBackgroundRMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.SammyBackgroundRMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.ScatteringRadius COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_ScatteringRadius.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.ScatteringRadius PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.SingleLevelBreitWigner COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_SingleLevelBreitWigner.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.SingleLevelBreitWigner PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.SpecialCase COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_SpecialCase.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.SpecialCase PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.SpinGroup COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_SpecialCase.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.SpinGroup PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.TabulatedBackgroundRMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_TabulatedBackgroundRMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.TabulatedBackgroundRMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyDependent COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyDependent.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyDependent PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentFissionWidths COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyDependentFissionWidths.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentFissionWidths PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentFissionWidthsJValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyDependentFissionWidthsJValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentFissionWidthsJValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentFissionWidthsLValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyDependentFissionWidthsLValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentFissionWidthsLValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentJValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyDependentJValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentJValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentLValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyDependentLValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyDependentLValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyIndependent COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyIndependent.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyIndependent PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT151.UnresolvedEnergyIndependentLValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT151_UnresolvedEnergyIndependentLValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT151.UnresolvedEnergyIndependentLValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF2.MT152.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF2_MT152_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF2.MT152.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF3.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF3_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF3.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF3.File COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF3_File.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF3.File PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF4.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF4_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF4.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF4.Isotropic COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF4_Isotropic.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF4.Isotropic PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF4.LegendreCoefficients COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF4_LegendreCoefficients.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF4.LegendreCoefficients PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF4.LegendreDistributions COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF4_LegendreDistributions.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF4.LegendreDistributions PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF4.MixedDistributions COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF4_MixedDistributions.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF4.MixedDistributions PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF4.TabulatedDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF4_TabulatedDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF4.TabulatedDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF4.TabulatedDistributions COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF4_TabulatedDistributions.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF4.TabulatedDistributions PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.DistributionFunction COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_DistributionFunction.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.DistributionFunction PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.EffectiveTemperature COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_EffectiveTemperature.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.EffectiveTemperature PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.EvaporationSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_EvaporationSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.EvaporationSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.GeneralEvaporationSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_GeneralEvaporationSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.GeneralEvaporationSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.MadlandNixSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_MadlandNixSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.MadlandNixSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.MaxwellianFissionSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_MaxwellianFissionSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.MaxwellianFissionSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.OutgoingEnergyDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_OutgoingEnergyDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.OutgoingEnergyDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.Parameter COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_Parameter.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.Parameter PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.PartialDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_PartialDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.PartialDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.Probability COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_Probability.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.Probability PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.TabulatedSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_TabulatedSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.TabulatedSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF5.WattSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF5_WattSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF5.WattSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.ChargedParticleElasticScattering COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_ChargedParticleElasticScattering.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.ChargedParticleElasticScattering PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.ContinuumEnergyAngle COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_ContinuumEnergyAngle.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.ContinuumEnergyAngle PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.DefinedElsewhere COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_DefinedElsewhere.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.DefinedElsewhere PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.DiscreteTwoBodyRecoils COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_DiscreteTwoBodyRecoils.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.DiscreteTwoBodyRecoils PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.DiscreteTwoBodyScattering COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_DiscreteTwoBodyScattering.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.DiscreteTwoBodyScattering PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.IsotropicDiscreteEmission COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_IsotropicDiscreteEmission.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.IsotropicDiscreteEmission PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LaboratoryAngleEnergy COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LaboratoryAngleEnergy.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LaboratoryAngleEnergy PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW1.KalbachMann COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW1_KalbachMann.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW1.KalbachMann PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW1.LegendreCoefficients COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW1_LegendreCoefficients.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW1.LegendreCoefficients PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW1.TabulatedDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW1_TabulatedDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW1.TabulatedDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW1.ThermalScatteringData COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW1_ThermalScatteringData.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW1.ThermalScatteringData PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW2.LegendreCoefficients COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW2_LegendreCoefficients.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW2.LegendreCoefficients PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW2.TabulatedDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW2_TabulatedDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW2.TabulatedDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW5.LegendreCoefficients COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW5_LegendreCoefficients.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW5.LegendreCoefficients PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW5.NuclearAmplitudeExpansion COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW5_NuclearAmplitudeExpansion.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW5.NuclearAmplitudeExpansion PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW5.NuclearPlusInterference COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW5_NuclearPlusInterference.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW5.NuclearPlusInterference PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW7.AngularDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW7_AngularDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW7.AngularDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.LAW7.EnergyDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_LAW7_EnergyDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.LAW7.EnergyDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.Multiplicity COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_Multiplicity.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.Multiplicity PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.NBodyPhaseSpace COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_NBodyPhaseSpace.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.NBodyPhaseSpace PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.ReactionProduct COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_ReactionProduct.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.ReactionProduct PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF6.Unknown COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF6_Unknown.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF6.Unknown PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT2.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT2_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT2.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT2.CoherentElastic COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT2_CoherentElastic.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT2.CoherentElastic PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT2.IncoherentElastic COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT2_IncoherentElastic.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT2.IncoherentElastic PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT2.MixedElastic COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT2_MixedElastic.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT2.MixedElastic PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT4.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT4_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT4.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT4.AnalyticalFunctions COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT4_AnalyticalFunctions.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT4.AnalyticalFunctions PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT4.EffectiveTemperature COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT4_EffectiveTemperature.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT4.EffectiveTemperature PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT4.ScatteringFunction COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT4_ScatteringFunction.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT4.ScatteringFunction PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT4.ScatteringLawConstants COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT4_ScatteringLawConstants.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT4.ScatteringLawConstants PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF7.MT4.TabulatedFunctions COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF7_MT4_TabulatedFunctions.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF7.MT4.TabulatedFunctions PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.FissionYieldData COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_FissionYieldData.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.FissionYieldData PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT454.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT454_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT454.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT457.AverageDecayEnergies COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT457_AverageDecayEnergies.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT457.AverageDecayEnergies PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT457.ContinuousSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT457_ContinuousSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT457.ContinuousSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT457.DecayMode COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT457_DecayMode.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT457.DecayMode PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT457.DecayModes COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT457_DecayModes.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT457.DecayModes PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT457.DecaySpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT457_DecaySpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT457.DecaySpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT457.DiscreteSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT457_DiscreteSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT457.DiscreteSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT457.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT457_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT457.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF8.MT459.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF8_MT459_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF8.MT459.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF9.ReactionProduct COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF9_ReactionProduct.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF9.ReactionProduct PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF9.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF9_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF9.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF10.ReactionProduct COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF10_ReactionProduct.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF10.ReactionProduct PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF10.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF10_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF10.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF12.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF12_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF12.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF12.Multiplicities COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF12_Multiplicities.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF12.Multiplicities PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF12.PartialMultiplicity COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF12_PartialMultiplicity.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF12.PartialMultiplicity PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF12.TotalMultiplicity COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF12_TotalMultiplicity.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF12.TotalMultiplicity PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF12.TransitionProbabilities COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF12_TransitionProbabilities.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF12.TransitionProbabilities PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF13.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF13_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF13.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF13.PartialCrossSection COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF13_PartialCrossSection.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF13.PartialCrossSection PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF13.TotalCrossSection COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF13_TotalCrossSection.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF13.TotalCrossSection PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF14.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF14_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF14.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF14.IsotropicDiscretePhoton COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF14_IsotropicDiscretePhoton.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF14.IsotropicDiscretePhoton PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF14.LegendreCoefficients COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF14_LegendreCoefficients.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF14.LegendreCoefficients PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF14.LegendreDistributions COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF14_LegendreDistributions.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF14.LegendreDistributions PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF14.TabulatedDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF14_TabulatedDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF14.TabulatedDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF14.TabulatedDistributions COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF14_TabulatedDistributions.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF14.TabulatedDistributions PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF15.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF15_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF15.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF15.OutgoingEnergyDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF15_OutgoingEnergyDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF15.OutgoingEnergyDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF15.Probability COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF15_Probability.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF15.Probability PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF15.TabulatedSpectrum COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF15_TabulatedSpectrum.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF15.TabulatedSpectrum PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF23.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF23_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF23.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.ContinuumEnergyAngle COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_ContinuumEnergyAngle.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.ContinuumEnergyAngle PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.DiscreteTwoBodyScattering COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_DiscreteTwoBodyScattering.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.DiscreteTwoBodyScattering PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.EnergyTransfer COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_EnergyTransfer.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.EnergyTransfer PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.LAW1.LegendreCoefficients COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_LAW1_LegendreCoefficients.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.LAW1.LegendreCoefficients PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.LAW2.TabulatedDistribution COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_LAW2_TabulatedDistribution.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.LAW2.TabulatedDistribution PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.Multiplicity COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_Multiplicity.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.Multiplicity PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF26.ReactionProduct COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF26_ReactionProduct.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF26.ReactionProduct PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF23.File COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF23_File.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF23.File PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF27.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF27_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF27.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF27.File COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF27_File.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF27.File PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF28.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF28_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF28.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF28.SubshellData COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF28_SubshellData.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF28.SubshellData PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.LimitedBreitWignerLValue COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_LimitedBreitWignerLValue.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.LimitedBreitWignerLValue PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.CompactCorrelationMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_CompactCorrelationMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.CompactCorrelationMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.CovarianceMatrix COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_CovarianceMatrix.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.CovarianceMatrix PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.LimitedMultiLevelBreitWigner COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_LimitedMultiLevelBreitWigner.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.LimitedMultiLevelBreitWigner PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.LimitedSingleLevelBreitWigner COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_LimitedSingleLevelBreitWigner.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.LimitedSingleLevelBreitWigner PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.ReichMooreScatteringRadiusUncertainties COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_ReichMooreScatteringRadiusUncertainties.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.ReichMooreScatteringRadiusUncertainties PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.ResonanceParameters COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_ResonanceParameters.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.ResonanceParameters PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.ShortRangeBreitWignerBlock COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_ShortRangeBreitWignerBlock.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.ShortRangeBreitWignerBlock PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.ShortRangeReichMooreBlock COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_ShortRangeReichMooreBlock.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.ShortRangeReichMooreBlock PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF32.MT151.ShortRangeRMatrixLimitedBlock COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF32_MT151_ShortRangeRMatrixLimitedBlock.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF32.MT151.ShortRangeRMatrixLimitedBlock PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF33.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF33_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF33.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF33.DerivedRatioToStandard COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF33_DerivedRatioToStandard.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF33.DerivedRatioToStandard PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF33.DerivedRedundant COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF33_DerivedRedundant.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF33.DerivedRedundant PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF33.ReactionBlock COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF33_ReactionBlock.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF33.ReactionBlock PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF34.LegendreBlock COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF34_LegendreBlock.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF34.LegendreBlock PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF34.ReactionBlock COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF34_ReactionBlock.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF34.ReactionBlock PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.MF34.Section COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_MF34_Section.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.MF34.Section PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.tree.File COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_Tree_File.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.tree.File PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.tree.Material COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_Tree_Material.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.tree.Material PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
add_test( NAME ENDFtk.python.tree.Tape COMMAND ${PYTHON_EXECUTABLE} -m unittest -v test/Test_ENDFtk_Tree_Tape.py WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/python )
set_tests_properties( ENDFtk.python.tree.Tape PROPERTIES ENVIRONMENT PYTHONPATH=${ENDFTK_PYTHONPATH}:$ENV{PYTHONPATH})
