#######################################################################
# Setup
#######################################################################

enable_testing()

FetchContent_MakeAvailable( Catch2 )

function( add_cpp_test name source )

  set( test_name "ENDFtk.${name}.test" )
  add_executable( ${test_name} ${source} )
  add_test( NAME ${test_name} COMMAND ${test_name} )
  target_link_libraries( ${test_name} PRIVATE ENDFtk )
  target_link_libraries( ${test_name} PRIVATE Catch2::Catch2WithMain )

  file( GLOB resources "resources/*" )
  foreach( resource ${resources} )
    file( COPY "${resource}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}" )
  endforeach()

endfunction()

#######################################################################
# Unit testing directories
#######################################################################

message( STATUS "Adding ENDFtk C++ unit testing" )

add_cpp_test( StructureDivision		StructureDivision.test.cpp )
add_cpp_test( file.Type		file/Type.test.cpp )
add_cpp_test( file.7		file/7.test.cpp )
add_cpp_test( file.2		file/2.test.cpp )
add_cpp_test( file.1		file/1.test.cpp )
add_cpp_test( file.8		file/8.test.cpp )
add_cpp_test( TextRecord		TextRecord.test.cpp )
add_cpp_test( ControlRecord		ControlRecord.test.cpp )
add_cpp_test( record		record.test.cpp )
add_cpp_test( TabulationRecord		TabulationRecord.test.cpp )
add_cpp_test( Tape		Tape.test.cpp )
add_cpp_test( tree.Section		tree/Section.test.cpp )
add_cpp_test( tree.Tape		tree/Tape.test.cpp )
add_cpp_test( tree.Material		tree/Material.test.cpp )
add_cpp_test( tree.File		tree/File.test.cpp )
add_cpp_test( Material		Material.test.cpp )
add_cpp_test( section.26		section/26.test.cpp )
add_cpp_test( section.3		section/3.test.cpp )
add_cpp_test( section.CovariancePairs		section/CovariancePairs.test.cpp )
add_cpp_test( section.27		section/27.test.cpp )
add_cpp_test( section.7.4.EffectiveTemperature		section/7/4/EffectiveTemperature.test.cpp )
add_cpp_test( section.7.4.ScatteringLawConstants		section/7/4/ScatteringLawConstants.test.cpp )
add_cpp_test( section.7.4.AnalyticalFunctions		section/7/4/AnalyticalFunctions.test.cpp )
add_cpp_test( section.7.4.TabulatedFunctions.ScatteringFunction		section/7/4/TabulatedFunctions/ScatteringFunction.test.cpp )
add_cpp_test( section.7.4.TabulatedFunctions		section/7/4/TabulatedFunctions.test.cpp )
add_cpp_test( section.7.451		section/7/451.test.cpp )
add_cpp_test( section.7.4		section/7/4.test.cpp )
add_cpp_test( section.7.451.ElementInformation		section/7/451/ElementInformation.test.cpp )
add_cpp_test( section.7.2.MixedElastic		section/7/2/MixedElastic.test.cpp )
add_cpp_test( section.7.2.IncoherentElastic		section/7/2/IncoherentElastic.test.cpp )
add_cpp_test( section.7.2.CoherentElastic		section/7/2/CoherentElastic.test.cpp )
add_cpp_test( section.7.2		section/7/2.test.cpp )
add_cpp_test( section.40.LevelBlock		section/40/LevelBlock.test.cpp )
add_cpp_test( section.Base		section/Base.test.cpp )
add_cpp_test( section.40		section/40.test.cpp )
add_cpp_test( section.RectangularMatrix		section/RectangularMatrix.test.cpp )
add_cpp_test( section.4.Isotropic		section/4/Isotropic.test.cpp )
add_cpp_test( section.4.MixedDistributions		section/4/MixedDistributions.test.cpp )
add_cpp_test( section.4.TabulatedDistribution		section/4/TabulatedDistribution.test.cpp )
add_cpp_test( section.4.LegendreCoefficients		section/4/LegendreCoefficients.test.cpp )
add_cpp_test( section.4.LegendreDistributions		section/4/LegendreDistributions.test.cpp )
add_cpp_test( section.4.TabulatedDistributions		section/4/TabulatedDistributions.test.cpp )
add_cpp_test( section.14		section/14.test.cpp )
add_cpp_test( section.10		section/10.test.cpp )
add_cpp_test( section.28		section/28.test.cpp )
add_cpp_test( section.23		section/23.test.cpp )
add_cpp_test( section.13.TotalCrossSection		section/13/TotalCrossSection.test.cpp )
add_cpp_test( section.13.PartialCrossSection		section/13/PartialCrossSection.test.cpp )
add_cpp_test( section.13		section/13.test.cpp )
add_cpp_test( section.4		section/4.test.cpp )
add_cpp_test( section.34		section/34.test.cpp )
add_cpp_test( section.14.TabulatedDistribution		section/14/TabulatedDistribution.test.cpp )
add_cpp_test( section.14.LegendreCoefficients		section/14/LegendreCoefficients.test.cpp )
add_cpp_test( section.14.IsotropicDiscretePhoton		section/14/IsotropicDiscretePhoton.test.cpp )
add_cpp_test( section.14.LegendreDistributions		section/14/LegendreDistributions.test.cpp )
add_cpp_test( section.14.TabulatedDistributions		section/14/TabulatedDistributions.test.cpp )
add_cpp_test( section.6.ReactionProduct		section/6/ReactionProduct.test.cpp )
add_cpp_test( section.6.ChargedParticleElasticScattering.LegendreCoefficients		section/6/ChargedParticleElasticScattering/LegendreCoefficients.test.cpp )
add_cpp_test( section.6.ChargedParticleElasticScattering.NuclearPlusInterference		section/6/ChargedParticleElasticScattering/NuclearPlusInterference.test.cpp )
add_cpp_test( section.6.ChargedParticleElasticScattering.NuclearAmplitudeExpansion		section/6/ChargedParticleElasticScattering/NuclearAmplitudeExpansion.test.cpp )
add_cpp_test( section.6.LaboratoryAngleEnergy		section/6/LaboratoryAngleEnergy.test.cpp )
add_cpp_test( section.6.Multiplicity		section/6/Multiplicity.test.cpp )
add_cpp_test( section.6.DiscreteTwoBodyScattering		section/6/DiscreteTwoBodyScattering.test.cpp )
add_cpp_test( section.6.NoLawDataGiven		section/6/NoLawDataGiven.test.cpp )
add_cpp_test( section.6.ContinuumEnergyAngle		section/6/ContinuumEnergyAngle.test.cpp )
add_cpp_test( section.6.ContinuumEnergyAngle.TabulatedDistribution		section/6/ContinuumEnergyAngle/TabulatedDistribution.test.cpp )
add_cpp_test( section.6.ContinuumEnergyAngle.LegendreCoefficients		section/6/ContinuumEnergyAngle/LegendreCoefficients.test.cpp )
add_cpp_test( section.6.ContinuumEnergyAngle.Base		section/6/ContinuumEnergyAngle/Base.test.cpp )
add_cpp_test( section.6.ContinuumEnergyAngle.ThermalScatteringData		section/6/ContinuumEnergyAngle/ThermalScatteringData.test.cpp )
add_cpp_test( section.6.ContinuumEnergyAngle.KalbachMann		section/6/ContinuumEnergyAngle/KalbachMann.test.cpp )
add_cpp_test( section.6.DiscreteTwoBodyRecoils		section/6/DiscreteTwoBodyRecoils.test.cpp )
add_cpp_test( section.6.IsotropicDiscreteEmission		section/6/IsotropicDiscreteEmission.test.cpp )
add_cpp_test( section.6.Unknown		section/6/Unknown.test.cpp )
add_cpp_test( section.6.DefinedElsewhere		section/6/DefinedElsewhere.test.cpp )
add_cpp_test( section.6.LaboratoryAngleEnergy.EnergyDistribution		section/6/LaboratoryAngleEnergy/EnergyDistribution.test.cpp )
add_cpp_test( section.6.LaboratoryAngleEnergy.AngularDistribution		section/6/LaboratoryAngleEnergy/AngularDistribution.test.cpp )
add_cpp_test( section.6.ChargedParticleElasticScattering		section/6/ChargedParticleElasticScattering.test.cpp )
add_cpp_test( section.6.DiscreteTwoBodyScattering.TabulatedDistribution		section/6/DiscreteTwoBodyScattering/TabulatedDistribution.test.cpp )
add_cpp_test( section.6.DiscreteTwoBodyScattering.LegendreCoefficients		section/6/DiscreteTwoBodyScattering/LegendreCoefficients.test.cpp )
add_cpp_test( section.6.NBodyPhaseSpace		section/6/NBodyPhaseSpace.test.cpp )
add_cpp_test( section.31		section/31.test.cpp )
add_cpp_test( section.33		section/33.test.cpp )
add_cpp_test( section.8.457		section/8/457.test.cpp )
add_cpp_test( section.8.459		section/8/459.test.cpp )
add_cpp_test( section.8.454		section/8/454.test.cpp )
add_cpp_test( section.8.457.DecayModes		section/8/457/DecayModes.test.cpp )
add_cpp_test( section.8.457.DiscreteSpectrum		section/8/457/DiscreteSpectrum.test.cpp )
add_cpp_test( section.8.457.ContinuousSpectrum		section/8/457/ContinuousSpectrum.test.cpp )
add_cpp_test( section.8.457.DecayMode		section/8/457/DecayMode.test.cpp )
add_cpp_test( section.8.457.DecaySpectrum		section/8/457/DecaySpectrum.test.cpp )
add_cpp_test( section.8.457.AverageDecayEnergies		section/8/457/AverageDecayEnergies.test.cpp )
add_cpp_test( section.8.FissionYieldData		section/8/FissionYieldData.test.cpp )
add_cpp_test( section.8.FissionYieldData.FissionProduct		section/8/FissionYieldData/FissionProduct.test.cpp )
add_cpp_test( section.35.SquareMatrix		section/35/SquareMatrix.test.cpp )
add_cpp_test( section.15		section/15.test.cpp )
add_cpp_test( section.5.Parameter		section/5/Parameter.test.cpp )
add_cpp_test( section.5.MaxwellianFissionSpectrum		section/5/MaxwellianFissionSpectrum.test.cpp )
add_cpp_test( section.5.EffectiveTemperature		section/5/EffectiveTemperature.test.cpp )
add_cpp_test( section.5.TabulatedSpectrum		section/5/TabulatedSpectrum.test.cpp )
add_cpp_test( section.5.GeneralEvaporationSpectrum		section/5/GeneralEvaporationSpectrum.test.cpp )
add_cpp_test( section.5.PartialDistribution		section/5/PartialDistribution.test.cpp )
add_cpp_test( section.5.Probability		section/5/Probability.test.cpp )
add_cpp_test( section.5.MadlandNixSpectrum		section/5/MadlandNixSpectrum.test.cpp )
add_cpp_test( section.5.WattSpectrum		section/5/WattSpectrum.test.cpp )
add_cpp_test( section.5.TabulatedSpectrum.OutgoingEnergyDistribution		section/5/TabulatedSpectrum/OutgoingEnergyDistribution.test.cpp )
add_cpp_test( section.5.EvaporationSpectrum		section/5/EvaporationSpectrum.test.cpp )
add_cpp_test( section.5.DistributionFunction		section/5/DistributionFunction.test.cpp )
add_cpp_test( section.6		section/6.test.cpp )
add_cpp_test( section.BaseWithoutMT		section/BaseWithoutMT.test.cpp )
add_cpp_test( section.DerivedRatioToStandard		section/DerivedRatioToStandard.test.cpp )
add_cpp_test( section.ReactionBlock		section/ReactionBlock.test.cpp )
add_cpp_test( section.9.ReactionProduct		section/9/ReactionProduct.test.cpp )
add_cpp_test( section.SquareMatrix		section/SquareMatrix.test.cpp )
add_cpp_test( section.2.152		section/2/152.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyDependent		section/2/151/UnresolvedEnergyDependent.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyIndependent.LValue		section/2/151/UnresolvedEnergyIndependent/LValue.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyIndependent.JValue		section/2/151/UnresolvedEnergyIndependent/JValue.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyIndependent		section/2/151/UnresolvedEnergyIndependent.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyDependent.LValue		section/2/151/UnresolvedEnergyDependent/LValue.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyDependent.JValue		section/2/151/UnresolvedEnergyDependent/JValue.test.cpp )
add_cpp_test( section.2.151.SpecialCase		section/2/151/SpecialCase.test.cpp )
add_cpp_test( section.2.151.SingleLevelBreitWigner		section/2/151/SingleLevelBreitWigner.test.cpp )
add_cpp_test( section.2.151.ReichMooreLValue		section/2/151/ReichMooreLValue.test.cpp )
add_cpp_test( section.2.151.Isotope		section/2/151/Isotope.test.cpp )
add_cpp_test( section.2.151.BreitWignerLValue.Resonance		section/2/151/BreitWignerLValue/Resonance.test.cpp )
add_cpp_test( section.2.151.ScatteringRadius		section/2/151/ScatteringRadius.test.cpp )
add_cpp_test( section.2.151.ReichMooreLValue.Resonance		section/2/151/ReichMooreLValue/Resonance.test.cpp )
add_cpp_test( section.2.151.MultiLevelBreitWigner		section/2/151/MultiLevelBreitWigner.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyDependentFissionWidths		section/2/151/UnresolvedEnergyDependentFissionWidths.test.cpp )
add_cpp_test( section.2.151.ReichMoore		section/2/151/ReichMoore.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.SpinGroup		section/2/151/RMatrixLimited/SpinGroup.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.ParticlePairs		section/2/151/RMatrixLimited/ParticlePairs.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.ResonanceParameters		section/2/151/RMatrixLimited/ResonanceParameters.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.BackgroundChannels		section/2/151/RMatrixLimited/BackgroundChannels.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.SammyBackgroundRMatrix		section/2/151/RMatrixLimited/SammyBackgroundRMatrix.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.NoBackgroundRMatrix		section/2/151/RMatrixLimited/NoBackgroundRMatrix.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.ResonanceChannels		section/2/151/RMatrixLimited/ResonanceChannels.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.FrohnerBackgroundRMatrix		section/2/151/RMatrixLimited/FrohnerBackgroundRMatrix.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited.TabulatedBackgroundRMatrix		section/2/151/RMatrixLimited/TabulatedBackgroundRMatrix.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyDependentFissionWidths.LValue		section/2/151/UnresolvedEnergyDependentFissionWidths/LValue.test.cpp )
add_cpp_test( section.2.151.UnresolvedEnergyDependentFissionWidths.JValue		section/2/151/UnresolvedEnergyDependentFissionWidths/JValue.test.cpp )
add_cpp_test( section.2.151.BreitWignerLValue		section/2/151/BreitWignerLValue.test.cpp )
add_cpp_test( section.2.151.RMatrixLimited		section/2/151/RMatrixLimited.test.cpp )
add_cpp_test( section.2.151		section/2/151.test.cpp )
add_cpp_test( section.DerivedRedundant		section/DerivedRedundant.test.cpp )
add_cpp_test( section.9		section/9.test.cpp )
add_cpp_test( section.26.ReactionProduct		section/26/ReactionProduct.test.cpp )
add_cpp_test( section.26.Multiplicity		section/26/Multiplicity.test.cpp )
add_cpp_test( section.26.DiscreteTwoBodyScattering		section/26/DiscreteTwoBodyScattering.test.cpp )
add_cpp_test( section.26.ContinuumEnergyAngle		section/26/ContinuumEnergyAngle.test.cpp )
add_cpp_test( section.26.EnergyTransfer		section/26/EnergyTransfer.test.cpp )
add_cpp_test( section.26.ContinuumEnergyAngle.LegendreCoefficients		section/26/ContinuumEnergyAngle/LegendreCoefficients.test.cpp )
add_cpp_test( section.26.DiscreteTwoBodyScattering.TabulatedDistribution		section/26/DiscreteTwoBodyScattering/TabulatedDistribution.test.cpp )
add_cpp_test( section.32.151.CompactRMatrixLimitedUncertainties		section/32/151/CompactRMatrixLimitedUncertainties.test.cpp )
add_cpp_test( section.32.151.CompactReichMooreUncertainties		section/32/151/CompactReichMooreUncertainties.test.cpp )
add_cpp_test( section.32.151.LimitedMultiLevelBreitWigner		section/32/151/LimitedMultiLevelBreitWigner.test.cpp )
add_cpp_test( section.32.151.CompactSingleLevelBreitWigner		section/32/151/CompactSingleLevelBreitWigner.test.cpp )
add_cpp_test( section.32.151.UnresolvedRelativeCovariances.CovarianceMatrix		section/32/151/UnresolvedRelativeCovariances/CovarianceMatrix.test.cpp )
add_cpp_test( section.32.151.UnresolvedRelativeCovariances.LValue		section/32/151/UnresolvedRelativeCovariances/LValue.test.cpp )
add_cpp_test( section.32.151.UnresolvedRelativeCovariances.JValue		section/32/151/UnresolvedRelativeCovariances/JValue.test.cpp )
add_cpp_test( section.32.151.ShortRangeRMatrixLimitedBlock		section/32/151/ShortRangeRMatrixLimitedBlock.test.cpp )
add_cpp_test( section.32.151.ReichMooreScatteringRadiusUncertainties		section/32/151/ReichMooreScatteringRadiusUncertainties.test.cpp )
add_cpp_test( section.32.151.LimitedSingleLevelBreitWigner		section/32/151/LimitedSingleLevelBreitWigner.test.cpp )
add_cpp_test( section.32.151.CompactMultiLevelBreitWigner		section/32/151/CompactMultiLevelBreitWigner.test.cpp )
add_cpp_test( section.32.151.ShortRangeReichMooreBlock		section/32/151/ShortRangeReichMooreBlock.test.cpp )
add_cpp_test( section.32.151.CompactCorrelationMatrix		section/32/151/CompactCorrelationMatrix.test.cpp )
add_cpp_test( section.32.151.UnresolvedRelativeCovariances		section/32/151/UnresolvedRelativeCovariances.test.cpp )
add_cpp_test( section.32.151.CompactReichMooreUncertainties.Resonance		section/32/151/CompactReichMooreUncertainties/Resonance.test.cpp )
add_cpp_test( section.32.151.GeneralRMatrixLimited		section/32/151/GeneralRMatrixLimited.test.cpp )
add_cpp_test( section.32.151.CompactBreitWignerUncertainties.Resonance		section/32/151/CompactBreitWignerUncertainties/Resonance.test.cpp )
add_cpp_test( section.32.151.CompactBreitWignerUncertainties		section/32/151/CompactBreitWignerUncertainties.test.cpp )
add_cpp_test( section.32.151.ScatteringRadiusCovariances		section/32/151/ScatteringRadiusCovariances.test.cpp )
add_cpp_test( section.32.151.ShortRangeRMatrixLimitedBlock.CovarianceMatrix		section/32/151/ShortRangeRMatrixLimitedBlock/CovarianceMatrix.test.cpp )
add_cpp_test( section.32.151.ShortRangeRMatrixLimitedBlock.ResonanceParameters		section/32/151/ShortRangeRMatrixLimitedBlock/ResonanceParameters.test.cpp )
add_cpp_test( section.32.151.CompactReichMoore		section/32/151/CompactReichMoore.test.cpp )
add_cpp_test( section.32.151.ShortRangeBreitWignerBlock		section/32/151/ShortRangeBreitWignerBlock.test.cpp )
add_cpp_test( section.32.151.GeneralReichMoore		section/32/151/GeneralReichMoore.test.cpp )
add_cpp_test( section.32.151.GeneralSingleLevelBreitWigner		section/32/151/GeneralSingleLevelBreitWigner.test.cpp )
add_cpp_test( section.32.151.LimitedBreitWignerLValue.Resonance		section/32/151/LimitedBreitWignerLValue/Resonance.test.cpp )
add_cpp_test( section.32.151.GeneralMultiLevelBreitWigner		section/32/151/GeneralMultiLevelBreitWigner.test.cpp )
add_cpp_test( section.32.151.CompactRMatrixLimitedUncertainties.SpinGroup		section/32/151/CompactRMatrixLimitedUncertainties/SpinGroup.test.cpp )
add_cpp_test( section.32.151.CompactRMatrixLimitedUncertainties.ParticlePairs		section/32/151/CompactRMatrixLimitedUncertainties/ParticlePairs.test.cpp )
add_cpp_test( section.32.151.CompactRMatrixLimitedUncertainties.ResonanceParameters		section/32/151/CompactRMatrixLimitedUncertainties/ResonanceParameters.test.cpp )
add_cpp_test( section.32.151.CompactRMatrixLimitedUncertainties.ResonanceChannels		section/32/151/CompactRMatrixLimitedUncertainties/ResonanceChannels.test.cpp )
add_cpp_test( section.32.151.CompactRMatrixLimited		section/32/151/CompactRMatrixLimited.test.cpp )
add_cpp_test( section.32.151.LimitedBreitWignerLValue		section/32/151/LimitedBreitWignerLValue.test.cpp )
add_cpp_test( section.5		section/5.test.cpp )
add_cpp_test( section.34.LegendreBlock		section/34/LegendreBlock.test.cpp )
add_cpp_test( section.34.ReactionBlock		section/34/ReactionBlock.test.cpp )
add_cpp_test( section.12		section/12.test.cpp )
add_cpp_test( section.1.460.DiscretePhotonMultiplicity		section/1/460/DiscretePhotonMultiplicity.test.cpp )
add_cpp_test( section.1.460.DiscretePhotons		section/1/460/DiscretePhotons.test.cpp )
add_cpp_test( section.1.460.ContinuousPhotons		section/1/460/ContinuousPhotons.test.cpp )
add_cpp_test( section.1.PolynomialMultiplicity		section/1/PolynomialMultiplicity.test.cpp )
add_cpp_test( section.1.452		section/1/452.test.cpp )
add_cpp_test( section.1.456		section/1/456.test.cpp )
add_cpp_test( section.1.451		section/1/451.test.cpp )
add_cpp_test( section.1.455		section/1/455.test.cpp )
add_cpp_test( section.1.458.ThermalPointComponents		section/1/458/ThermalPointComponents.test.cpp )
add_cpp_test( section.1.458.TabulatedComponents		section/1/458/TabulatedComponents.test.cpp )
add_cpp_test( section.1.458.EnergyReleaseComponent		section/1/458/EnergyReleaseComponent.test.cpp )
add_cpp_test( section.1.458.PolynomialComponents		section/1/458/PolynomialComponents.test.cpp )
add_cpp_test( section.1.458		section/1/458.test.cpp )
add_cpp_test( section.1.455.DecayConstants		section/1/455/DecayConstants.test.cpp )
add_cpp_test( section.1.455.EnergyDependentConstants		section/1/455/EnergyDependentConstants.test.cpp )
add_cpp_test( section.1.455.EnergyIndependentConstants		section/1/455/EnergyIndependentConstants.test.cpp )
add_cpp_test( section.1.TabulatedMultiplicity		section/1/TabulatedMultiplicity.test.cpp )
add_cpp_test( section.1.460		section/1/460.test.cpp )
add_cpp_test( section.12.TransitionProbabilities.Transition		section/12/TransitionProbabilities/Transition.test.cpp )
add_cpp_test( section.12.TransitionProbabilities		section/12/TransitionProbabilities.test.cpp )
add_cpp_test( section.12.Multiplicities		section/12/Multiplicities.test.cpp )
add_cpp_test( section.12.TotalMultiplicity		section/12/TotalMultiplicity.test.cpp )
add_cpp_test( section.12.PartialMultiplicity		section/12/PartialMultiplicity.test.cpp )
add_cpp_test( section.28.SubshellData.Transition		section/28/SubshellData/Transition.test.cpp )
add_cpp_test( section.28.SubshellData		section/28/SubshellData.test.cpp )
add_cpp_test( section.15.TabulatedSpectrum		section/15/TabulatedSpectrum.test.cpp )
add_cpp_test( section.15.PartialDistribution		section/15/PartialDistribution.test.cpp )
add_cpp_test( section.15.Probability		section/15/Probability.test.cpp )
add_cpp_test( section.15.TabulatedSpectrum.OutgoingEnergyDistribution		section/15/TabulatedSpectrum/OutgoingEnergyDistribution.test.cpp )
add_cpp_test( section.10.ReactionProduct		section/10/ReactionProduct.test.cpp )
add_cpp_test( section.35		section/35.test.cpp )
add_cpp_test( record.Zipper		record/Zipper.test.cpp )
add_cpp_test( record.Base		record/Base.test.cpp )
add_cpp_test( record.InterpolationBase		record/InterpolationBase.test.cpp )
add_cpp_test( record.Tail		record/Tail.test.cpp )
add_cpp_test( record.Sequence		record/Sequence.test.cpp )
add_cpp_test( InterpolationRecord		InterpolationRecord.test.cpp )
add_cpp_test( tree		tree.test.cpp )
add_cpp_test( HeadRecord		HeadRecord.test.cpp )
add_cpp_test( ListRecord		ListRecord.test.cpp )
add_cpp_test( TapeIdentification		TapeIdentification.test.cpp )
add_cpp_test( InterpolationSequenceRecord		InterpolationSequenceRecord.test.cpp )
add_cpp_test( DirectoryRecord		DirectoryRecord.test.cpp )

add_cpp_test( gsection.1.451  gsection/1/451g.test.cpp )
add_cpp_test( gsection.3      gsection/3g.test.cpp )
add_cpp_test( gsection.5.455  gsection/5/455g.test.cpp )
add_cpp_test( gsection.5.18   gsection/5/18g.test.cpp )
add_cpp_test( gsection.6      gsection/6g.test.cpp )
add_cpp_test( gsection.33     gsection/33g.test.cpp )

add_cpp_test( tree.GSection  tree/GSection.test.cpp )
add_cpp_test( tree.GFile     tree/GFile.test.cpp )
add_cpp_test( tree.GMaterial tree/GMaterial.test.cpp )
add_cpp_test( tree.GTape     tree/GTape.test.cpp )
